# Generated by Django 4.1.2 on 2023-03-18 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CategoryApp', '0013_alter_cartmodel_vendorid_alter_productmodel_vendorid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetailsmodel',
            name='pincode',
        ),
    ]
