# Generated by Django 5.2 on 2025-04-14 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CategoryApp', '0015_cartmodel_checkin_date_cartmodel_checkin_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartModel',
        ),
    ]
