# Generated by Django 5.2 on 2025-04-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CategoryApp', '0016_delete_cartmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('vendorId', models.IntegerField(default=1)),
                ('productId', models.IntegerField()),
                ('productPrice', models.IntegerField(default='')),
                ('qty', models.IntegerField(default='')),
                ('totalPrice', models.IntegerField(default='')),
                ('orderId', models.IntegerField()),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('checkin_time', models.TimeField()),
                ('checkout_time', models.TimeField()),
                ('guests', models.IntegerField()),
            ],
        ),
    ]
