# Generated by Django 5.2 on 2025-04-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CategoryApp', '0017_cartmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='checkin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='checkin_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='checkout_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='checkout_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='guests',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
